version: '3.4'

services:
  pulsar-test-node:
    image: pulsar-test-node
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
    depends_on: [pulsar]

  pulsar:
    image: apachepulsar/pulsar:latest
    entrypoint: bin/pulsar standalone
    hostname: pulsar